apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nls0w7an5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nls0w7an5-java-quarkus-gitops