apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nls0w7an5-java-quarkus
  janus-idp.io/tekton: nls0w7an5-java-quarkus
  backstage.io/kubernetes-id: nls0w7an5-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nls0w7an5-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
